In [1]:
from keras.preprocessing.image import ImageDataGenerator
from skimage import io
import glob
import os

In [2]:
datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=45,     
        width_shift_range=0.2,   
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='constant',
        cval=125) 

In [3]:
import numpy as np
from skimage import io
import os
from PIL import Image

In [8]:
image_directory = 'D:/Tasks/Coconut/Finalized Data Set/Immatured_Singles/'
SIZE = 128
dataset = []

In [14]:
def check_file_type(image_folder_path, allowed_extensions=None):
    if allowed_extensions is None:
        allowed_extensions = ['.jpg']

    no_files_in_folder = len(glob.glob(image_folder_path+"/*")) 
    extension_type = ""
    no_files_allowed = 0

    for ext in allowed_extensions:
      no_files_allowed = len(glob.glob(image_folder_path+"/*"+ext))
      if no_files_allowed > 0:
        extension_type = ext
        break

    assert no_files_in_folder == no_files_allowed, "Found more than one extensions"
    return extension_type

In [15]:
check_file_type('D:/Tasks/Coconut/Finalized Data Set/Immatured_Singles', None)

'.jpg'

In [9]:
my_images = os.listdir(image_directory)
for i, image_name in enumerate(my_images):
    if (image_name.split('.')[1] == 'JPG'):
        image = io.imread(image_directory + image_name)
        image = Image.fromarray(image, 'RGB')
        image = image.resize((SIZE,SIZE))
        dataset.append(np.array(image))

x = np.array(dataset)

In [10]:
print(x)

[[[[195 180 138]
   [187 168 124]
   [174 157 114]
   ...
   [210 198 155]
   [211 198 153]
   [212 199 154]]

  [[197 180 139]
   [193 174 131]
   [189 171 129]
   ...
   [209 196 151]
   [214 200 153]
   [214 197 149]]

  [[196 176 134]
   [193 174 130]
   [194 176 132]
   ...
   [211 198 153]
   [214 201 152]
   [220 202 152]]

  ...

  [[100  89  58]
   [ 94  85  56]
   [ 92  83  57]
   ...
   [228 215 177]
   [229 217 179]
   [229 215 176]]

  [[ 88  76  52]
   [ 93  83  56]
   [ 99  88  61]
   ...
   [228 212 168]
   [229 213 170]
   [232 217 176]]

  [[ 95  84  56]
   [ 91  79  50]
   [ 98  88  59]
   ...
   [231 214 170]
   [227 211 165]
   [231 215 172]]]


 [[[108 114  44]
   [112 132  45]
   [141 124  64]
   ...
   [131 107  37]
   [190 164  79]
   [183 157  74]]

  [[181 161 107]
   [127 137  59]
   [ 93 103  31]
   ...
   [ 90  73  24]
   [163 144  74]
   [155 139  79]]

  [[175 157 107]
   [176 164  98]
   [ 96 121  31]
   ...
   [140 115  49]
   [133 110  45]
   [131 112

In [13]:
i = 0
for batch in datagen.flow(x, batch_size=32,  
                          save_to_dir='D:\Academics\Level 6\Final Project\Data_Set\augmented', 
                          save_prefix='aug', 
                          save_format='jpg'):
    i += 1
    if i > 8:
        break